### PR TITLE
Fix stricture

### PR DESCRIPTION
**Pull request by hexmode**
Fix some Perl::Critic issues and misc bugs

### CODE REVIEW

**Comment by hexmode** [comment]
ping @moy

**Review by anarcat — APPROVED** [review]
lgtm, can't wait to have CI to keep that on track

**Comment by hexmode** [comment]
so, the editorconfig action works (when I do pull requests against my own fork, at least).  The perlcritic action finds problems and provides a json file with the results, but doesn't seem to add annotations the way it is supposed to.

**Review by moy — APPROVED** [review]
Looks good, but the history is currently messy. @hexmode , do you want to clean up your history (rebase -i & friends) or shall I squash while merging?

**Comment by hexmode** [comment]
This should be cleaner now.

I'm not completely happy with the actions, but that is an upstream issue for now.

**Comment by moy** [comment]
Not sure why the GH action wasn't running for the PR, but it dit run for the push:

Unfortunately, there are still a bunch of perlcritic issues reported:

https://github.com/Git-Mediawiki/Git-Mediawiki/runs/5492222203?check_suite_focus=true

**Comment by hexmode** [comment]
I take back what I said about being not happy with the actions.  For some reason, it is working on this PR but not on my own.  Probably need to update how it is invoked.

Well, at least I have the reports now :smile:

**Comment by hexmode** [comment]
I was planning to rebase tonight. Thanks! 

Mark A. Hershberger 
NicheWork LLC 
717-271-1084

**Pull request merged**
