### PR TITLE
Make hardcoding of slash replacement and suffix configurable

### PR DESCRIPTION
**Pull request by hexmode**
For example, .mediawiki files are rendered as wikitext on Github, so a
user could change the suffix to .mediawiki and push a copy of their
wiki to Github and have it render (somewhat) correctly.

### CODE REVIEW

**Comment by moy** [comment]
I think https://github.com/git/git/pull/355 is slightly better in this regard (it goes one step further, making the extension actually configurable), except that it was posted it the wrong place.

@anarcat, any opinion?

**Comment by hexmode** [comment]
> I think [git/git#355](https://github.com/git/git/pull/355) is slightly better in this regard (it goes one step further, making the extension actually configurable), except that it was posted it the wrong place.

I like the configurability bit, but it doesn't update Mediawiki.pm

**Comment by anarcat** [comment]
> I think git/git#355 is slightly better in this regard (it goes one step further, making the extension actually configurable), except that it was posted it the wrong place.

Agreed.

> I like the configurability bit, but it doesn't update Mediawiki.pm

Seems like something that should be fairly to fix..? :)

**Comment by hexmode** [comment]
Thinking about this: it is better for this configurable to be for all mediawiki-based remotes instead of on a per-wiki basis.

**Comment by moy** [comment]
> Thinking about this: it is better for this configurable to be for all mediawiki-based remotes instead of on a per-wiki basis.

It is already the case: `git config` reads the per-repo `.git/config` and the `~/.gitconfig`. However, the variable name should make it clear that it's a Mediawiki-specific variable (and therefore avoid any name clash with non-mediawiki stuff). Perhaps `mwFilenameExtension`?

Be careful not to put too much in a single pull-request (there's essentially 0 bandwidth to review stuff on our side...).

**Comment by hexmode** [comment]
> Be careful not to put too much in a single pull-request (there's essentially 0 bandwidth to review stuff on our side...).

Undersood.  Would you be willing to give maintenance to this repository to the [MediaWiki Stakeholdders](https://www.mediawiki.org/wiki/MediaWiki_Stakeholders'_Group) @MWStake ?

**Comment by moy** [comment]
> > Be careful not to put too much in a single pull-request (there's essentially 0 bandwidth to review stuff on our side...).
> 
> Undersood. Would you be willing to give maintenance to this repository to the [MediaWiki Stakeholdders](https://www.mediawiki.org/wiki/MediaWiki_Stakeholders'_Group) @MWStake ?

Are you part of this group? Indeed, we're not fighting to keep maintainership ;-). I'm no longer a user of Git-Mediawiki, hence it's hard to find time and motivation to maintain it. @anarcat volunteered to help, but has a lot on his plate and didn't promise to be a good maintainer either.

I just want to make sure we don't transfer to any unknown person, if only for security ("Hi, I'm a nice guy and I want write access to your repo" seems to be a valid attack to introduce backdoors in software these days ;-) ).

**Comment by hexmode** [comment]
I'm the current president of the group.  #mwstake is a User Group affiliated with the Wikimedia Foundation and as you can see from our [bylaws](https://mwstake.org/mwstake/wiki/Bylaws#Vision.2C_Purpose.2C_and_Activities) (which we are about to make official) this project is well within scope.

If your hesitant because of the commits I've made in this series... well, I didn't have the Travis tests working on my system and had trouble working on them.

I'm about to make this all easier to review my squashing and force-pushing.

**Comment by anarcat** [comment]
> Are you part of this group? Indeed, we're not fighting to keep maintainership ;-). I'm no longer a user of Git-Mediawiki, hence it's hard to find time and motivation to maintain it.

FWIW, that's also my current status as well. Found this projec, thought "awesome", tweaked it to get it to work with a *single* site, and then tried to contribute something back. But I really don't have much time either, but I'll spend the time to properly delegate when we get there. :)

**Comment by moy** [comment]
On my side, I have no objection in giving maintainer-ship to MWStake.

**Comment by anarcat** [comment]
@hexmode all the changes you're pushing to master branch show up in this merge request, which is now mixing unrelated commits. it's also sending us a notification every time you make a push. so i will close the PR until you make a specific topic branch for this PR...

sorry for the inconvenience, but it's just too noisy for my poor little inbox. :)

**Pull request closed without merging**
